### ISSUE TITLE
Add code for level.finish()

### ISSUE THREAD

**Issue by abishekvashok** [abishekvashok/labyrinth#3]
Add code for level.finish() which deletes the current tiles in the body (along with the div that was created).

**Comment by YashKumarVerma** [comment]
Claiming

**Comment by abishekvashok** [comment]
@YashKumarVerma sure :)

**Comment by abishekvashok** [comment]
@YashKumarVerma any updates bro?

**Comment by YashKumarVerma** [comment]
sending in

**Comment by YashKumarVerma** [comment]
@abishekvashok where do i inject my code ?

**Comment by YashKumarVerma** [comment]
![image](https://user-images.githubusercontent.com/14032427/34687365-818a169e-f4d4-11e7-9516-7daaa023aba1.png)

**Comment by YashKumarVerma** [comment]
pr sent
