### ISSUE TITLE
Add secondary code for level.finish()

### ISSUE THREAD

**Issue by abishekvashok** [abishekvashok/labyrinth#4]
Trigger loadNextLevel() function in level.finish() and define it. Add code in it to call the gui.js needy functions.

**Comment by samyakbvs** [comment]
CLAIMING!

**Comment by abishekvashok** [comment]
@samyakbvs sure. For this if you don't see the level.finish() function nor the loadNextLevel(), please define both.  level.finish() should be a prototype of level class.

**Comment by abishekvashok** [comment]
@samyakbvs any updates bro?
